### ISSUE TITLE
Demo offline

### ISSUE THREAD

**Issue by Gachl** [TheBroox/TextAdventure.js#1]
Hello

The demo (http://textadventure-thebroox.rhcloud.com/) linked on the npm page (https://www.npmjs.com/package/text-adventure) is not available anymore. Any chance on getting it back up?

Thanks.

**Comment by TheBroox** [comment]
Thanks for the heads up. It looks like RedHat has killed the hosting it was on. I will see about migrating it elsewhere. In the meantime I will update the documentation to at least not contain a dead link. Pulling the repo, running install and the code will give you the same experience.
